#!/usr/bin/env python3

import time
import pyspeedtest


start_time = str(time.asctime( time.localtime(time.time()) ))
start_time_string_1 = start_time.replace(" ","_")
start_time_string = start_time_string_1.replace(":","_")


def main():
    txt = open(start_time_string,"w")
    txt.close()
    last_time = time.time()

    write_test(last_time, 0, 0, 0)

    while True:
    	if (time.time() < 60.0 + last_time):
    		time.sleep(5)

    	else:
    		last_time = time.time()
    		st = pyspeedtest.SpeedTest()
    		last_ping = st.ping()
    		last_dl = st.download() / 1000000
    		last_ul = st.upload() / 1000000
    		write_test(last_time, last_ping, last_dl, last_ul)
    		time.sleep(20)

			
			
def write_test(time, ping, dl, ul):
    txt = open(start_time_string, "a")
    txt.write(str(time))
    txt.write("\t")
    txt.write(str(ping))
    txt.write("\t")
    txt.write(str(dl))
    txt.write("\t")
    txt.write(str(ul))
    txt.write("\n")
    txt.close()			

main()
